# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fmessenger.proto\"\x07\n\x05\x45mpty\"\x1c\n\nInitClient\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\"\x1f\n\x0b\x43heckResult\x12\x10\n\x08is_mafia\x18\x01 \x01(\x08\"\x19\n\tUniversal\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x0b\x43hatMessage\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t2\xb1\x03\n\x06Maphia\x12+\n\x0bWaitForGame\x12\x0b.InitClient\x1a\x0b.InitClient\"\x00\x30\x01\x12%\n\nGetClients\x12\x06.Empty\x1a\x0b.InitClient\"\x00\x30\x01\x12 \n\x07\x43onnect\x12\x0b.InitClient\x1a\x06.Empty\"\x00\x12\x1f\n\x06\x45ndDay\x12\x0b.InitClient\x1a\x06.Empty\"\x00\x12!\n\x08VoteKill\x12\x0b.InitClient\x1a\x06.Empty\"\x00\x12\"\n\tKillNight\x12\x0b.InitClient\x1a\x06.Empty\"\x00\x12$\n\x05\x43heck\x12\x0b.InitClient\x1a\x0c.CheckResult\"\x00\x12%\n\x0bPostMessage\x12\x0c.ChatMessage\x1a\x06.Empty\"\x00\x12,\n\x0bGetMessages\x12\x0b.InitClient\x1a\x0c.ChatMessage\"\x00\x30\x01\x12$\n\x07GetRole\x12\x0b.InitClient\x1a\n.Universal\"\x00\x12(\n\x08StartDay\x12\x0b.InitClient\x1a\x0b.InitClient\"\x00\x30\x01\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=26,
)


_INITCLIENT = _descriptor.Descriptor(
  name='InitClient',
  full_name='InitClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='InitClient.author', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=56,
)


_CHECKRESULT = _descriptor.Descriptor(
  name='CheckResult',
  full_name='CheckResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_mafia', full_name='CheckResult.is_mafia', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=89,
)


_UNIVERSAL = _descriptor.Descriptor(
  name='Universal',
  full_name='Universal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='Universal.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=116,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='author', full_name='ChatMessage.author', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='ChatMessage.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['InitClient'] = _INITCLIENT
DESCRIPTOR.message_types_by_name['CheckResult'] = _CHECKRESULT
DESCRIPTOR.message_types_by_name['Universal'] = _UNIVERSAL
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

InitClient = _reflection.GeneratedProtocolMessageType('InitClient', (_message.Message,), {
  'DESCRIPTOR' : _INITCLIENT,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:InitClient)
  })
_sym_db.RegisterMessage(InitClient)

CheckResult = _reflection.GeneratedProtocolMessageType('CheckResult', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESULT,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:CheckResult)
  })
_sym_db.RegisterMessage(CheckResult)

Universal = _reflection.GeneratedProtocolMessageType('Universal', (_message.Message,), {
  'DESCRIPTOR' : _UNIVERSAL,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:Universal)
  })
_sym_db.RegisterMessage(Universal)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)



_MAPHIA = _descriptor.ServiceDescriptor(
  name='Maphia',
  full_name='Maphia',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=164,
  serialized_end=597,
  methods=[
  _descriptor.MethodDescriptor(
    name='WaitForGame',
    full_name='Maphia.WaitForGame',
    index=0,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_INITCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetClients',
    full_name='Maphia.GetClients',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_INITCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='Maphia.Connect',
    index=2,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndDay',
    full_name='Maphia.EndDay',
    index=3,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VoteKill',
    full_name='Maphia.VoteKill',
    index=4,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='KillNight',
    full_name='Maphia.KillNight',
    index=5,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Check',
    full_name='Maphia.Check',
    index=6,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_CHECKRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostMessage',
    full_name='Maphia.PostMessage',
    index=7,
    containing_service=None,
    input_type=_CHATMESSAGE,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMessages',
    full_name='Maphia.GetMessages',
    index=8,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_CHATMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRole',
    full_name='Maphia.GetRole',
    index=9,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_UNIVERSAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartDay',
    full_name='Maphia.StartDay',
    index=10,
    containing_service=None,
    input_type=_INITCLIENT,
    output_type=_INITCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAPHIA)

DESCRIPTOR.services_by_name['Maphia'] = _MAPHIA

# @@protoc_insertion_point(module_scope)
